name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
        mysql:
            image: mysql:5.7
            env:
                MYSQL_ROOT_PASSWORD: password
            ports:
            - 32574:3306
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
            sudo /etc/init.d/mysql start
            sudo mysql < ./sql/create-pds.sql
            mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=vammdk1_Proceso-de-software
